apiVersion: v1
kind: Service
metadata:
  name: opensearch-service
  namespace: opensearch
spec:
  selector:
    app: opensearch
  clusterIP: 10.96.10.1
  ports:
  - name: dashboard
    port: 5601
    targetPort: 5601
  - name: rest
    port: 9200
    targetPort: 9200