apiVersion: v1
kind: PersistentVolume
metadata:
  name: opensearch-storage
  labels:
    type: local
spec:
  claimRef:
    name: opensearch-storage
    namespace: opensearch
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt/disk/opensearch-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - commonprod01.server.alexander-aust.de
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-storage
  namespace: opensearch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi