apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-tls
  dnsNames:
    - commonprod01.server.alexander-aust.de
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
