apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitwarden-secret
  namespace: bitwarden
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: bitwarden-secret
    creationPolicy: Owner
  data:
  - secretKey: smtp-password
    remoteRef:
      key: env
      property: smtp-password