apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-es
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-css
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secret
  dataFrom:
    - extract:
        key: mailserver/roundcube
