apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  dovecot.conf: |
    disable_plaintext_auth = yes
    mail_privileged_group = mail
    mail_home=/srv/mail/users/%n
    mail_location = maildir:~/
    first_valid_uid = 100
    ssl = required
    ssl_cert = </etc/dovecot/tls.crt
    ssl_key = </etc/dovecot/tls.key
    protocols = " imap pop3 "
    auth_username_format = %n
    
    userdb {
      driver = static
      args = uid=101 gid=102
    }
    auth_mechanisms = plain login
    
    passdb {
      driver = pam
      args = failure_show_msg=yes keycloak
    }
    service auth {
      inet_listener {
      port = 60400
      }
    }
    service imap-login {
      inet_listener imap {
        port = 0
      }
      inet_listener imaps {
        port = 993
        ssl = yes
      }
    }
