kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postfix-storage-claim
  namespace: mailserver
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-deployment
  namespace: mailserver
  labels:
    app: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      volumes:
      - name: postfix-loginmaps
        configMap:
          name: postfix-loginmaps
      - name: postfix-config
        configMap:
          name: postfix-config
      - name: postfix-master-config
        configMap:
          name: postfix-master-config
      - name: postfix-virtualmaps
        configMap:
          name: postfix-virtualmaps

      - name: opendkim-config
        configMap:
          name: opendkim-config
      - name: opendkim-key-secret
        secret:
          secretName: opendkim-key-secret

      - name: letsencrypt-fullchain-cert
        configMap:
          name: letsencrypt-fullchain-cert
      - name: letsencrypt-private-key-secret
        secret:
          secretName: letsencrypt-private-key-secret

      - name: postfix-storage
        persistentVolumeClaim:
          claimName: postfix-storage-claim
      containers:
      - name: postfix
        image: alaust/postfix:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: postfix-loginmaps
          mountPath: "/etc/postfix/loginmaps"
          subPath: loginmaps
        - name: postfix-virtualmaps
          mountPath: "/etc/postfix/virtualmaps"
          subPath: virtualmaps
        - name: postfix-config
          mountPath: "/etc/postfix/main.cf"
          subPath: main.cf
        - name: postfix-master-config
          mountPath: "/etc/postfix/master.cf"
          subPath: master.cf

        - name: postfix-storage
          mountPath: "/var/mail"

        - name: opendkim-config
          mountPath: "/etc/opendkim/opendkim.conf"
          subPath: opendekim.conf
        - name: opendkim-key-secret
          mountPath: "/etc/opendkim/keys/alexander-aust.de/default.private"
          subPath: default.private

        - name: letsencrypt-fullchain-cert
          mountPath: "/etc/postfix/fullchain.pem"
          subPath: fullchain.pem
        - name: letsencrypt-private-key-secret
          mountPath: "/etc/postfix/privkey.pem"
          subPath: privkey.pem