apiVersion: v1
kind: Service
metadata:
  name: postfix-entrypoint
  namespace: mailserver
spec:
  selector:
    app: postfix
  clusterIP: 10.96.1.10
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: smtp-submission
      port: 587
      targetPort: 587