apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opendkim-key-secret
  namespace: mailserver
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: opendkim-key-secret
    creationPolicy: Owner
    template:
      data:
        default.private: "{{ .default_private }}"
  data:
  - secretKey: default_private
    remoteRef:
      key: postfix/dkim
      property: default.private