apiVersion: v1
kind: Service
metadata:
  name: gitea-entrypoint
  namespace: gitea
spec:
  clusterIP: 10.43.11.10
  selector:
    app: gitea
  ports:
    - name: http
      port: 3000
    - name: ssh
      port: 2222
      targetPort: 22