apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-css
spec:
  provider:
    vault:
      server: "http://vault-service.vault:8200"
      path: "k8s/"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "67f27b60-f290-3e2b-6dd8-bcb548fbe4e9"
          secretRef:
            name: "k8s-secret-injector"
            namespace: "external-secrets"
            key: "secret-id"
