apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: vault
  ports:
    - name: ui
      port: {{ .Values.service.ports.ui }}
