apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wireguard-secret
  namespace: wireguard
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: wireguard-secret
    creationPolicy: Owner
  data:
  - secretKey: ui-password
    remoteRef:
      key: env
      property: ui-password